//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeShell.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FBProfilePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FBProfilePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeShell.Test.Resources.FBProfilePageResources", typeof(FBProfilePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;pagelet_welcome_box&apos;]/ul/li[1]/div/div/a.
        /// </summary>
        internal static string ActualUsernameTextXPath {
            get {
                return ResourceManager.GetString("ActualUsernameTextXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;u_0_e&apos;]/a.
        /// </summary>
        internal static string HomeLinkXPath {
            get {
                return ResourceManager.GetString("HomeLinkXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;u_jsonp_2_8&apos;]/div/div[5]/div/ul/li[2]/button.
        /// </summary>
        internal static string PostButtonXPath {
            get {
                return ResourceManager.GetString("PostButtonXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/div[1]/div[2]/div[1]/div/div[2]/div[2]/div/div[3]/div/div[4]/div/div[1]/div/div/div/div/div/div/div[2]/div[1]/div[3].
        /// </summary>
        internal static string PostedStatusXPath {
            get {
                return ResourceManager.GetString("PostedStatusXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;u_jsonp_2_h&apos;].
        /// </summary>
        internal static string StatusTextBoxXPath {
            get {
                return ResourceManager.GetString("StatusTextBoxXPath", resourceCulture);
            }
        }
    }
}
